baseurl = "https://im5tu.io/"
title = "CodeWithStu's Blog"
languageCode = "en-gb"
canonifyURLs = true
enableRobotsTXT = true
cleanDestinationDir = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[minify]
  minifyOutput = true
  [minify.tdewolff.html]
    keepQuotes = true

[sitemap]
  priority = 0.5
  changeFreq = "monthly"