baseurl = "https://im5tu.io/"
title = "CodeWithStu's Blog"
languageCode = "en-gb"
canonifyURLs = true
enableRobotsTXT = true
cleanDestinationDir = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy"]
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[minify]
  disableML = true
  minifyOutput = true
  [minify.tdewolff.html]
    keepQuotes = true

[sitemap]
  priority = 0.5
  changeFreq = "monthly"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]