baseurl = "https://im5tu.io/"
title = "Stuart Blackler's Blog"
languageCode = "en-us"
theme = "hello-friend-ng"
metaDataFormat = "json"
enableRobotsTXT = true
pygmentsuseclasses = true
ignorefiles = [ "content/draft/.*" ]

[Author]
  name = "Stuart Blackler"

[permalinks]
  article = "article/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "I'm Stu, welcome to my online home. You can connect with me on one of the socials below :)"

  # Logo
  [params.Logo]
    logoText = "im5tu.io"

  # Social icons
  [params.portrait]
    path = "/img/profile.png"
    alt = "Portrait"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/CodeWithStu"

  [[params.social]]
    name = "github"
    url  = "https://bit.ly/im5tu-gh"

  [[params.social]]
    name = "linkedin"
    url  = "https://bit.ly/im5tu-li"

  [[params.social]]
    name = "youtube"
    url  = "https://codewithstu.tv"

  [[params.social]]
    name = "discord"
    url  = "https://discord.codewithstu.tv"

  [[params.social]]
    name = "facebook"
    url  = "https://facebook.com/codewithstu"

[markup]
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.

[minify]
  minifyOutput = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "articles"
    name       = "Blog"
    url        = "article/"

  [[menu.main]]
    identifier = "rss"
    name       = "RSS Feed"
    url        = "/article/index.xml"

  [[menu.main]]
    identifier = "news"
    name       = "Discord"
    url        = "https://discord.codewithstu.tv"

  [[menu.main]]
    identifier = "sponsorship"
    name       = "Sponsorship"
    url        = "/sponsorship"

  [[menu.main]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com/CodeWithStu"

  [[menu.main]]
    identifier = "youtube"
    name       = "YouTube"
    url        = "https://bit.ly/im5tu-yt-sub"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "RSS"]