name: Merge Schedule
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 0 8 * * *
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}